version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: socialmetrics_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: socialmetrics_db
      MYSQL_USER: user_api
      MYSQL_PASSWORD: api_password
    ports:
      - "3306:3306"
    volumes:
      - ./data/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: socialmetrics_pma
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data: